#! /bin/bash

python scripts/generate_scene_continuous.py ds_continuous=pick_to_basket_1
python scripts/generate_scene_continuous.py ds_continuous=pick_to_basket_2

python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_nestle_1
python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_nestle_2

python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_vanish_1
python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_vanish_2

python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_duff_1
python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_duff_2

python scripts/generate_scene_continuous.py ds_continuous=pick_from_floor_1
python scripts/generate_scene_continuous.py ds_continuous=pick_from_floor_2