#! /bin/bash

WORKERS=2

python scripts/generate_scene_continuous.py ds_continuous=pick_to_basket_1 ds_continuous.num_workers=$WORKERS
python scripts/generate_scene_continuous.py ds_continuous=pick_to_basket_2 ds_continuous.num_workers=$WORKERS

python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_nestle_1 ds_continuous.num_workers=$WORKERS
python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_nestle_2 ds_continuous.num_workers=$WORKERS

python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_vanish_1 ds_continuous.num_workers=$WORKERS
python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_vanish_2 ds_continuous.num_workers=$WORKERS

python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_duff_1 ds_continuous.num_workers=$WORKERS
python scripts/generate_scene_continuous.py ds_continuous=move_from_board_to_board_duff_2 ds_continuous.num_workers=$WORKERS

python scripts/generate_scene_continuous.py ds_continuous=pick_from_floor_1 ds_continuous.num_workers=$WORKERS
python scripts/generate_scene_continuous.py ds_continuous=pick_from_floor_2 ds_continuous.num_workers=$WORKERS

python scripts/generate_scene_continuous.py ds_continuous=open_showcase assets=assets_downscaled ds_continuous.num_workers=$WORKERS
python scripts/generate_scene_continuous.py ds_continuous=open_fridge assets=assets_downscaled ds_continuous.num_workers=$WORKERS
